### ISSUE TITLE
Use user/password instead of API key?

### ISSUE THREAD

**Issue by luketlancaster** [taz77/sendgrid-php-ng#10]
Couldn't find this anywhere (probably just missed it while looking through the code)...how do I pass a username/password to the Client instead of an api key? Can I do this _and_ pass an options array? Has this been taken out? Sorry if the answer is obvious, thanks for the help!

**Comment by taz77** [comment]
You cannot use username and password, only API keys are supported. Username/password is a very bad practice from a security perspective so it was removed from the library. SendGrid also took this approach in the V3 of their API and only API keys are supported on the V3.

**Comment by luketlancaster** [comment]
Awesome, exactly what I needed to know. Totally understand, and thanks for the quick reply!

**Comment by taz77** [comment]
Not a problem. I am working on V3 upgrade when I have time. I'm about to devote a few days to it real soon.

**Comment by luketlancaster** [comment]
Feel free to close this down! Or you could use it as a "remove references to password/update docs" if you like as well. Good luck with the work on it!
