### ISSUE TITLE
How is it established? Content-Type

### ISSUE THREAD

**Issue by llavillaccama** [taz77/sendgrid-php-ng#22]
Hi Brady,

Could you please give me a clue on how I can set the 'Content-Type'.

I'm migrating to Sendgrid, the previous function I used is:

`mail('test@test.com', 'Example 001', 'Content example', "From: GoldMine WebImport <no-reply@test.com>\r\nContent-Type: text/x-gm-impdata\r\n" )`

**I tried this configuration with sendgrid and the data for CRM import does not work for me.**
`$email
    ->addTo('test@test.com')
    ->addHeader('Content-Type', 'text/x-gm-impdata')
    ->setFrom('GoldMine WebImport <apply@test.com>')
    ->setSubject('Example 001')
    ->setText($Body);
    $sendgrid->send($email);`

Regards

**Comment by taz77** [comment]
Been two years. Going to close this.
