### ISSUE TITLE
SMTPAPI header was invalid

### ISSUE THREAD

**Issue by drfuzetto** [taz77/sendgrid-php-ng#23]
When I add a template_id it gets posted to SendGrid but SendGrid blocks it from being sent out.
I am getting this:
"This email was not sent because the SMTPAPI header was invalid."

Doesn't really say what is invalid.  If I don't include the template_id, the email is sent ok.

Anyone else have this issue?

**Comment by taz77** [comment]
The template features are mostly untested. The V3 upgrade also removes all of the SMTPAPI code.

**Comment by taz77** [comment]
Closing due to time. V3 upgrade has to happen soon.
