### ISSUE TITLE
Improve error/exception handling

### ISSUE THREAD

**Issue by vladpavlovic** [taz77/sendgrid-php-ng#26]
Currently, when a Guzzle ClientException is encountered, the `postRequest` method outputs an error message and the var_dumps the entire exception.  

The exception contains the Request object as well, which itself contains the bearer token for auth to SendGrid. This is a security vulnerability since it exposes the token.

This code never ran previously due to #24 but it will need to be addressed alongside it.

**Comment by taz77** [comment]
This issue did not close automatically with the merge.

**Comment by taz77** [comment]
Now I have to roll this into the V3 upgrade
