### ISSUE TITLE
PHP 8.1 errors

### ISSUE THREAD

**Issue by webfaqtory** [taz77/sendgrid-php-ng#44]
Errors displayed by V2.0.5 with PHP 8.1

Deprecated function: Return type of SendGrid\Mail\Mail::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in include() (line 22 of /mnt/wsl/PHYSICALDRIVE0p1/www/unctad/target/vendor/fastglass/sendgrid/src/Mail/Mail.php).

Deprecated function: Return type of SendGrid\Mail\Personalization::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in include() (line 22 of /mnt/wsl/PHYSICALDRIVE0p1/www/unctad/target/vendor/fastglass/sendgrid/src/Mail/Personalization.php).

Deprecated function: Return type of SendGrid\Mail\SandBoxMode::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in include() (line 18 of /mnt/wsl/PHYSICALDRIVE0p1/www/unctad/target/vendor/fastglass/sendgrid/src/Mail/SandBoxMode.php).

Deprecated function: Return type of SendGrid\Mail\Category::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in include() (line 17 of /mnt/wsl/PHYSICALDRIVE0p1/www/unctad/target/vendor/fastglass/sendgrid/src/Mail/Category.php).

Deprecated function: Return type of SendGrid\Mail\Subject::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in include() (line 17 of /mnt/wsl/PHYSICALDRIVE0p1/www/unctad/target/vendor/fastglass/sendgrid/src/Mail/Subject.php).

Deprecated function: Return type of SendGrid\Mail\EmailAddress::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in include() (line 18 of /mnt/wsl/PHYSICALDRIVE0p1/www/unctad/target/vendor/fastglass/sendgrid/src/Mail/EmailAddress.php).

Deprecated function: Return type of SendGrid\Mail\Content::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in include() (line 17 of /mnt/wsl/PHYSICALDRIVE0p1/www/unctad/target/vendor/fastglass/sendgrid/src/Mail/Content.php).

Deprecated function: Return type of SendGrid\Mail\Attachment::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in include() (line 18 of /mnt/wsl/PHYSICALDRIVE0p1/www/unctad/target/vendor/fastglass/sendgrid/src/Mail/Attachment.php).

Deprecated function: Return type of SendGrid\Mail\TrackingSettings::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in include() (line 17 of /mnt/wsl/PHYSICALDRIVE0p1/www/unctad/target/vendor/fastglass/sendgrid/src/Mail/TrackingSettings.php).

Deprecated function: Return type of SendGrid\Mail\ClickTracking::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in include() (line 18 of /mnt/wsl/PHYSICALDRIVE0p1/www/unctad/target/vendor/fastglass/sendgrid/src/Mail/ClickTracking.php).

Deprecated function: Return type of SendGrid\Mail\OpenTracking::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in include() (line 22 of /mnt/wsl/PHYSICALDRIVE0p1/www/unctad/target/vendor/fastglass/sendgrid/src/Mail/OpenTracking.php).

**Comment by gabesullice** [comment]
@taz77, can you tag a new release now that #42 is merged? That should resolve this issue.

**Comment by taz77** [comment]
Yes, I meant to but got distracted. Will write myself a reminder for tomorrow.

**Comment by danheisel** [comment]
Glad I stumbled onto this. A few of my sites were hitting this error after upgrading to PHP 8.1 when using the Drupal SendGrid Integration module. Will this be sent out to a release soon? Thanks!

**Comment by taz77** [comment]
Starting to work on it now. I do most of my open source stuff at night after my day job.

**Comment by taz77** [comment]
New version is now on Packagist

**Comment by gabesullice** [comment]
Thank you so much!

**Comment by danheisel** [comment]
Wonderful! Thank you!!

**Comment by krisolafson** [comment]
Super!
