### ISSUE TITLE
Incorret filter param

### ISSUE THREAD

**Issue by ghost** [taz77/sendgrid-php-ng#8]
At Email.php on setTemplateId function (after looking on sendgrid smtp api)

```
public function setTemplateId($templateId) {
    $this->addFilter('templates', 'enabled', 1);
    $this->addFilter('templates', 'template_id', $templateId);

    return $this;
}
```

I believe that should be "enable" and not "enabled".

**Comment by taz77** [comment]
You are right! But I think this is only for V3 API. Which I am still working on.

https://sendgrid.com/docs/API_Reference/Web_API_v3/Transactional_Templates/smtpapi.html

**Comment by ghost** [comment]
Ah, I got it. Thanks and keep with the good work :+1:

**Comment by taz77** [comment]
I've come back to the V3 API and I am trying to get it finished this week. It was a lot of rewriting, to the point that I should have just started from scratch.

**Comment by taz77** [comment]
Committed the change to the V3 branch.
