### ISSUE TITLE
Incorrect Client setup method being used in example documentation

### ISSUE THREAD

**Issue by r7l** [taz77/sendgrid-php-ng#9]
Hello, after trying sendgrid/sendgrid i would like to try this library but i can't get it to work. I've installed it with `composer require fastglass/sendgrid` and it installed just fine. But when running one of your examples it just breaks with this error:

`Fatal error: Class 'SendGrid' not found in /srv/http/test/sendgrid-test.php on line 5`

I have the needed require statement for vendor. Is there anything i've missed? Does this only work with Drupal?

**Comment by taz77** [comment]
Sorry for replying so late. This library is not Drupal specific.

Let me double check my examples. I have not use the example since I wrote it!

**Comment by r7l** [comment]
Thanks would love to try this library when able to get it going.

**Comment by taz77** [comment]
Easy fix. `$sendgrid = new SendGrid('YOUR_SENDGRID_APIKEY');` should be `$sendgrid = new SendGrid\Client('YOUR_SENDGRID_APIKEY');`

**Comment by taz77** [comment]
`SendGrid` is just the namespace, it isn't a class.

**Comment by taz77** [comment]
I just pushed a new version of the wrapper
